name: link_on
description: A Soical Media Flutter App.
version: 2.3.0+88
publish_to: none
environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_localization: ^0.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: any
  lottie: any
  google_mobile_ads: ^5.3.1
  dio: ^5.4.0
  nb_utils: ^7.0.4
  story_view: ^0.16.5
  cached_network_image: any
  flutter_html: any
  provider: ^6.1.1
  share_plus: ^7.2.2
  visibility_detector: ^0.3.3
  permission_handler: ^11.3.0
  shimmer: ^2.0.0
  emojis: ^0.9.9
  flutter_dotenv: ^5.1.0
  flutter_portal: ^1.1.3
  date_format: ^2.0.7
  http_auth: ^1.0.1
  mime_type: ^1.0.0
  url_launcher: ^6.1.9
  expandable: ^5.0.1
  comment_tree: ^0.3.0
  flutter_app_badger: ^1.5.0
  overlay_support: ^2.1.0
  device_info_plus: ^9.1.2
  google_nav_bar: ^5.0.6
  detectable_text_field: ^3.0.2
  lecle_flutter_link_preview: ^0.0.1+3
  youtube_player_flutter: ^9.1.1
  fraction: any
  http_parser: ^4.0.2
  flutter_downloader: ^1.11.8
  flutter_device_type: ^0.4.0
  html: ^0.15.4
  webview_flutter: ^4.10.0
  rxdart: ^0.27.7
  syncfusion_flutter_charts: ^26.2.14
  screenshot: ^3.0.0
  flutter_swiper_null_safety: any
  flutter_speed_dial: ^7.0.0
  google_generative_ai: ^0.4.3
  dart_openai: ^5.1.0
  qr_flutter: ^4.1.0
  app_links: ^6.1.4
  uuid: any
  path: any
  http: any
  camera: ^0.11.1
  # Database
  sqflite: ^2.0.0+4
  # social sign in
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^7.1.0
  # twitter_login: ^4.4.2
  linkedin_login: ^3.1.3
  # notification
  onesignal_flutter: ^5.2.4
  awesome_notifications: ^0.10.1
  # agora
  agora_rtc_engine: ^6.5.0
  agora_rtm:
    git:
      url: https://github.com/rufus-op/agora_rtm_latest.git
  # Media
  path_provider: ^2.0.11
  gallery_saver:
    git:
      url: https://github.com/rufus-op/gallery_saver_latest.git
  file_picker:
    git:
      url: https://github.com/rufus-op/file_picker.git
  image_picker: ^1.0.7
  video_editor: ^3.0.0
  image_cropper: ^9.0.0
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/rufus-op/ffmpeg_latest.git
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  just_audio: ^0.9.36
  flutter_sound: ^9.4.20
  audio_waveforms: ^1.0.5
  audio_video_progress_bar: ^2.0.2
  cached_video_player_plus: ^3.0.3
  flick_video_player: ^0.9.0
  video_compress: ^3.1.3
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  deepar_flutter:
    git:
      url: https://github.com/rufus-op/deepar_flutter.git
      ref: green
  # Location
  google_maps_flutter: ^2.3.1
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  # payment
  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
  flutterwave_standard:
    git:
      url: https://github.com/rufus-op/flutterwave_standard_latest
  flutter_stripe: ^10.1.1
  razorpay_web:
    git:
      url: https://github.com/rufus-op/razorpay_web_latest.git
  nsfw_detector_flutter: ^1.0.5

dependency_overrides:
  iris_method_channel: ^2.2.0
  permission_handler: ^11.3.0
  wakelock_windows: ^0.2.1
  win32: 5.6.0
  http: ^1.0.0
  webview_flutter_android: ^4.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/lancherIcon/app_icon.png"

flutter:
  generate: true
  uses-material-design: true

  # fonts:
  #   - family: Avalon
  #     fonts:
  #      - asset: assets/font/Avalon-regular.ttf
  #      - asset: assets/font/Avalon-bold.ttf
  #        weight: 700

  assets:
    - assets/images/
    - assets/anim/
    - assets/filters/
    - assets/previews/
    - assets/
    - assets/font/
    - assets/lutspreview/
    - assets/icons/
    - assets/Basic/
    - assets/luts/
    - assets/fbImages/
    - lib/localization/languages/
    - .env
