name: link_on
description: A Social Media Flutter App.
version: 2.3.0+88
publish_to: none

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: any
  shimmer: ^2.0.0
  flutter_speed_dial: ^7.0.0
  flutter_swiper_null_safety: any
  google_nav_bar: ^5.0.6

  # Localization
  flutter_localization: ^0.2.2

  # State Management
  provider: ^6.1.1

  # Animation & Graphics
  lottie: any
  emojis: ^0.9.9

  # Networking
  dio: ^5.4.0
  http: ^1.0.0
  http_auth: ^1.0.1
  http_parser: ^4.0.2
  url_launcher: ^6.1.9

  # Caching & Storage
  cached_network_image: any
  path_provider: ^2.0.11
  sqflite: ^2.0.0+4
  mime_type: ^1.0.0
  gallery_saver:
    git:
      url: https://github.com/rufus-op/gallery_saver_latest.git

  # File Handling
  file_picker:
    git:
      url: https://github.com/rufus-op/file_picker.git

  # Permissions & Device Info
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  flutter_device_type: ^0.4.0

  # Utilities
  nb_utils: ^7.0.4
  share_plus: ^7.2.2
  visibility_detector: ^0.3.3
  flutter_dotenv: ^5.1.0
  flutter_portal: ^1.1.3
  date_format: ^2.0.7
  expandable: ^5.0.1
  comment_tree: ^0.3.0
  flutter_app_badger: ^1.5.0
  overlay_support: ^2.1.0
  detectable_text_field: ^3.0.2
  lecle_flutter_link_preview: ^0.0.1+3
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  app_links: ^6.1.4
  uuid: any
  path: any
  rxdart: ^0.27.7
  screenshot: ^3.0.0
  dart_openai: ^5.1.0
  google_generative_ai: ^0.4.3
  nsfw_detector_flutter: ^1.0.5

  # Auth & Social Sign-In
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^7.1.0
  linkedin_login: ^3.1.3

  # Media & Editor
  image_picker: ^1.0.7
  image_cropper: ^9.0.0
  video_editor: ^3.0.0
  ffmpeg_kit_flutter_full_gpl: ^6.0.0
  video_player: ^2.9.2
  cached_video_player_plus: ^3.0.3
  flick_video_player: ^0.9.0
  video_compress: ^3.1.3
  audioplayers: ^6.1.0
  just_audio: ^0.9.36
  flutter_sound: ^9.4.20
  audio_waveforms: ^1.0.5
  audio_video_progress_bar: ^2.0.2
  camera: ^0.11.1
  fraction: any

  # Realtime & Live Features
  agora_rtc_engine: ^6.5.0
  agora_rtm:
    git:
      url: https://github.com/rufus-op/agora_rtm_latest.git
  deepar_flutter:
    git:
      url: https://github.com/rufus-op/deepar_flutter.git
      ref: green

  # Payments
  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
  flutterwave_standard:
    git:
      url: https://github.com/rufus-op/flutterwave_standard_latest
  flutter_stripe: ^10.1.1
  razorpay_web:
    git:
      url: https://github.com/rufus-op/razorpay_web_latest.git

  # Notifications
  onesignal_flutter: ^5.2.4
  awesome_notifications: ^0.10.1

  # Location & Maps
  google_maps_flutter: ^2.3.1
  geocoding: ^3.0.0
  geolocator: ^10.1.0

  # WebView
  webview_flutter: ^4.10.0
  html: ^0.15.4

  # QR & Barcode
  qr_flutter: ^4.1.0

dependency_overrides:
  iris_method_channel: ^2.2.0
  permission_handler: ^11.3.0
  wakelock_windows: ^0.2.1
  win32: 5.6.0
  http: ^1.0.0
  webview_flutter_android: ^4.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcherIcon/app_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
    - assets/filters/
    - assets/previews/
    - assets/
    - assets/font/
    - assets/lutspreview/
    - assets/icons/
    - assets/Basic/
    - assets/luts/
    - assets/fbImages/
    - lib/localization/languages/
    - .env
